### ISSUE TITLE
Разработка схемы "Вики-страница"

### ISSUE THREAD

**Issue by extremecodetv** [VkSharp/Vk.Api.Schema#14]
- [x] Разработать типы описывающие вики-страницу
- [x] Разработать типы параметры для взаимодействия с вики-страницами

[Документация типа вики-страница](https://vk.com/dev/objects/page)
[Документация для параметров взаимодействия с вики](https://vk.com/dev/pages.get)

**Comment by Valentin447** [comment]
Работаю над этой задачей.
