### ISSUE TITLE
Разработка схем "Чат" и "Личное сообщение"

### ISSUE THREAD

**Issue by extremecodetv** [VkSharp/Vk.Api.Schema#16]
- [x] Разработать тип описывающий сообщение
- [x] Разработать тип описывающий чат
- [x] Разработать вложенные типы сообщений и чата
- [x] Разработать типы параметры для взаимодействия с сообщениями и чатами

[Документация типа личное сообщение](https://vk.com/dev/objects/message)
[Документация типа чат](https://vk.com/dev/objects/chat)

[Документация для параметров взаимодействия с личными сообщениями и чатами](https://vk.com/dev/messages.get)

**Comment by Valentin447** [comment]
Работаю над этой задачей.
