### ISSUE TITLE
Разработка схемы "Опрос"

### ISSUE THREAD

**Issue by extremecodetv** [VkSharp/Vk.Api.Schema#2]
- [x] Разработать тип описывающий "Опрос"
- [x] Разработать вложенные типы опроса
- [x] Разработать типы параметры для взаимодействия с опросам

[Документация типа опрос](https://vk.com/dev/objects/poll)
[Документация для параметров взаимодействия с опросами](https://vk.com/dev/polls.addVote)

**Comment by nickolasKrayn** [comment]
Беру эти таски на себя

**Comment by extremecodetv** [comment]
Задача закрыта
