### ISSUE TITLE
Разработка схемы "Обсуждения"

### ISSUE THREAD

**Issue by extremecodetv** [VkSharp/Vk.Api.Schema#4]
- [x] Разработать типы описывающие обсуждения
- [x] Разработать типы описывающие комментарии к обсуждениям
- [x] Разработать вложенные типы обсуждений
- [x] Разработать типы параметры для взаимодействия с обсуждениями и комментариями

[Документация типа обсуждение](https://vk.com/dev/objects/topic)
[Документация типа комментарий к обсуждению](https://vk.com/dev/objects/comment_board)

[Документация для параметров взаимодействия с обсуждениями](https://vk.com/dev/board.getTopics)

**Comment by Valentin447** [comment]
Работаю над этой задачей
